### ISSUE TITLE
Crear las carpetas de Auth, Filter, Hero, Productos, Sobre Nostros con sus archivos correspondientes dentro de components

### ISSUE THREAD

**Issue by valentinalbornozz** [CodeSystem2022/Proyecto-Final-Ecommerce-Chaskibunes-Cuarto-semestre#4]
Dentro de cada carpeta tiene que ir su componente, en este caso tiene que ser la carpeta auth y userProfile.jsx, la carpeta filter y filter.jsx, la carpeta productos con porductos.jsx que contiene la logica de los productos para la pagina de inicio, productoStyle.css para los estilos y products.jsx que almacena en un array todos los productos que tiene el ecommerce y ademas hay que crear la carpeta de sobre nosotros que es un apartado dentro de inicio que contiene unos iconos y que ofrecemos en muy resumidas cuentas y el archivo css

**Comment by mairacar** [comment]
Finalizado
