### ISSUE TITLE
Crear las siguientes paginas y carpetas de inicio, about, productos, contactos con sus respectivas paginas

### ISSUE THREAD

**Issue by valentinalbornozz** [CodeSystem2022/Proyecto-Final-Ecommerce-Chaskibunes-Cuarto-semestre#6]
cada pagina debe estar dentro del apartado de paginas dentro de la carpeta correpondiente en la cual el inicio traera  el hero, sobre nosotros y los productos.

**Comment by MANASES200** [comment]
finalizado exitosamente.
