### ISSUE TITLE
Crear las siguientes paginas y carpetas de login, register, perfil, checkout page, confirmación con sus respectivas paginas

### ISSUE THREAD

**Issue by valentinalbornozz** [CodeSystem2022/Proyecto-Final-Ecommerce-Chaskibunes-Cuarto-semestre#7]
cada pagina debe estar dentro del apartado de paginas dentro de la carpeta correpondiente en la cual el inicio traera el login, register y los estilos para los mismos, el perfil, la checkout page para finalizar los pagos y la pagina de confirmación luego de terminar el pago.

**Comment by kevinAleFunes** [comment]
Finalizado
